//export const Form Definitions
export const formOne: any[] = [
  {
    label: 'Cluster Name',
    fieldType: 'input',
    controlName: 'clusterName',
    type: 'text',
    placeholder: '',
    errorMessage: 'Cluster Name is required',
  },
  {
    label: 'Bootstrap Servers',
    fieldType: 'input',
    controlName: 'bootstrapServers',
    type: 'text',
    placeholder: '',
    errorMessage: 'Bootstrap Servers are required',
  },
];

export const formTwo: any[] = [
  {
    label: 'Security Protocol',
    fieldType: 'select',
    controlName: 'secProtocol',
    type: 'select',
    placeholder: '',
    options: [
      { label: 'Plain Text', value: 'PT' },
      { label: 'SSL', value: 'SSL' },
      { label: 'SASL Plain Text', value: 'SASL PT' },
      { label: 'SASL SSL', value: 'SASL SSL' },
    ],
    selected: 'PT',
    hint: 'Protocol used to communicate with brokers',
  },
  {
    label: 'SASL Mechanism',
    fieldType: 'select',
    controlName: 'saslMech',
    type: 'select',
    placeholder: '',
    options: [
      { label: '', value: null },
      { label: 'GSSAPI', value: 'GSSAPI' },
      { label: 'PLAIN', value: 'PLAIN' },
      { label: 'SCRAM-SHA-256', value: 'SCRAM-SHA-256' },
      { label: 'SCRAM-SHA-512', value: 'SCRAM-SHA-512' },
    ],
    hint: 'SASL mechanism to use for authentication',
  },
  {
    label: 'SASL User Name',
    fieldType: 'input',
    controlName: 'saslUsername',
    type: 'text',
    placeholder: '',
    hint: 'SASL username for use with the PLAIN and SASL-SCRAM mechanisms',
  },
  {
    label: 'SASL Password',
    fieldType: 'input',
    controlName: 'saslPassword',
    type: 'password',
    placeholder: '',
    hint: 'SASL password for use with the PLAIN and SASL-SCRAM mechanism',
  },
  {
    label: "Path to client's private key file",
    fieldType: 'input',
    controlName: 'pathToClientPrivkf',
    type: 'text',
    placeholder: '',
    hint: "Path to client's private key (PEM) used for authentication",
  },
  {
    label: 'SSL Key Password',
    fieldType: 'input',
    controlName: 'sslKeyPassword',
    type: 'password',
    placeholder: '',
    hint: "Password for client's certificate",
  },
  {
    label: "Path to client's public key file",
    fieldType: 'input',
    controlName: 'pathToClientPubkf',
    type: 'text',
    placeholder: '',
    hint: "Path to client's public key (PEM) used for authentication",
  },
  {
    label: 'Path to root CA certificates file',
    fieldType: 'input',
    controlName: 'pathToRootCACertFile',
    type: 'text',
    placeholder: '',
    hint: "Path to CA certificate file for verifying the broker's certificate",
  },
];

export const formThree: any[] = [
  {
    label: 'Schema Registry URL',
    fieldType: 'input',
    controlName: 'schemaRegistryUrl',
    type: 'text',
    placeholder: '',
    hint: 'Schema Registry URL',
  },
  {
    label: 'Basic Auth User Info',
    fieldType: 'input',
    controlName: 'basicAuthUserInfo',
    type: 'password',
    placeholder: '',
    hint: 'Schema Registry Basic Auth User Info',
  },
  {
    label: 'Auto-register schemas',
    fieldType: 'slide-toggle',
    controlName: 'autoRegisterSchemas',
    type: 'slide-toggle',
    hint: 'Automatically register new schemas when producing messages',
  },
];

export const formFour: any[] = [
  {
    label: 'Consumer Group Id Prefix',
    fieldType: 'input',
    controlName: 'cgIdPrefix',
    type: 'text',
    placeholder: '',
    hint: 'Consumer Group Id is concatenation of the prefix and random Id',
  },
  {
    label: 'APIVersion Request',
    fieldType: 'slide-toggle',
    controlName: 'apiVerRequest',
    type: 'slide-toggle',
    placeholder: '',
    hint: "Request broker's supported API versions",
  },
  {
    label: 'APIVersion Fallback ms',
    fieldType: 'input',
    controlName: 'apiVerFallbackMs',
    type: 'text',
    hint: 'Dictates how long broker version fallback is used',
  },
  {
    label: 'Broker Version Fallback',
    fieldType: 'input',
    controlName: 'brokerVerFallback',
    type: 'text',
    hint: 'If ApiVersionRequest fails, the fallback version will be used',
  },
  {
    label: 'Reconnect Backoff Max ms',
    fieldType: 'input',
    controlName: 'reconnectBackoffMaxMs',
    type: 'text',
    hint: 'Maximum time to wait before reconnecting to a broker',
  },
  {
    label: 'Message Max Bytes',
    fieldType: 'input',
    controlName: 'msgMaxBytes',
    type: 'text',
    hint: 'Maximum Kafka protocol request message size',
  },
  {
    label: 'Receive Message Max Bytes',
    fieldType: 'input',
    controlName: 'receiveMsgMaxBytes',
    type: 'text',
    hint: 'Maximum Kafka protocol request message size',
  },
  {
    label: 'Fetch Error Backoff ms',
    fieldType: 'input',
    controlName: 'fetchErrBackoffMs',
    type: 'text',
    hint: 'How long to postpone the next fetch request',
  },
  {
    label: 'Fetch Max bytes',
    fieldType: 'input',
    controlName: 'fetchMaxBytes',
    type: 'text',
    hint: 'Maximum amount of data the broker shall return for a Fetch request',
  },
  {
    label: 'Max Partition Fetch Bytes',
    fieldType: 'input',
    controlName: 'maxPartitionFetchBytes',
    type: 'text',
    hint: 'Initial maximum number of bytes per topic+partition to request',
  },
  {
    label: 'Queued Max Messages Kbytes',
    fieldType: 'input',
    controlName: 'queuedMaxMsgKbytes',
    type: 'text',
    hint: 'Maximum number of kilobytes per topic+partition in local consumer queue',
  },
  {
    label: 'Queued Min Messages',
    fieldType: 'input',
    controlName: 'queuedMinMsgs',
    type: 'text',
    hint: 'Minimum number of messages per topic+partition in local consumer queue',
  },
  {
    label: 'Check Crcs',
    fieldType: 'slide-toggle',
    controlName: 'checkCrcs',
    type: 'slide-toggle',
    hint: 'Verify CRC32 of consumed messages',
  },
];
